-- ============================================================
-- 01_tags.sql — Governance Object Tags
-- Task: B06
-- Owner: CoCo
-- Schema: SUPPLY_CHAIN_FORGE.GOVERNED
-- ============================================================

USE DATABASE SUPPLY_CHAIN_FORGE;
USE SCHEMA GOVERNED;

-- 1. Create Tags with strict allowed values
CREATE TAG IF NOT EXISTS ENTITY_TYPE
    ALLOWED_VALUES 'SUPPLIER', 'PART', 'PLANT', 'INVENTORY', 'CUSTOMER', 'ORDER', 'ORDER_LINE', 'SHIPMENT', 'SOURCING'
    COMMENT = 'Entity classification across the supply chain ontology graph';

CREATE TAG IF NOT EXISTS SOURCE_SYSTEM
    ALLOWED_VALUES 'ERP', 'WMS', 'TMS', 'SRM'
    COMMENT = 'Originating source system schema';

CREATE TAG IF NOT EXISTS SENSITIVITY
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED'
    COMMENT = 'Data confidentiality and governance classification';

CREATE TAG IF NOT EXISTS PII
    ALLOWED_VALUES 'TRUE', 'FALSE'
    COMMENT = 'Personally Identifiable Information flag';

CREATE TAG IF NOT EXISTS METRIC_FAMILY
    ALLOWED_VALUES 'DELIVERY', 'FULFILLMENT', 'INVENTORY', 'COST'
    COMMENT = 'Canonical metric family association';

-- 2. Apply Tags to Source Tables & Key Columns
-- SRM_SOURCE
ALTER TABLE SUPPLY_CHAIN_FORGE.SRM_SOURCE.LFA1 
    SET TAG ENTITY_TYPE = 'SUPPLIER', SOURCE_SYSTEM = 'SRM', SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.SRM_SOURCE.LFA1 
    MODIFY COLUMN EMAIL SET TAG PII = 'TRUE', SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.SRM_SOURCE.LFA1 
    MODIFY COLUMN ZTERM SET TAG SENSITIVITY = 'RESTRICTED';

ALTER TABLE SUPPLY_CHAIN_FORGE.SRM_SOURCE.MARA 
    SET TAG ENTITY_TYPE = 'PART', SOURCE_SYSTEM = 'SRM', SENSITIVITY = 'INTERNAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.SRM_SOURCE.MARA 
    MODIFY COLUMN STPRS SET TAG SENSITIVITY = 'RESTRICTED', METRIC_FAMILY = 'COST';

ALTER TABLE SUPPLY_CHAIN_FORGE.SRM_SOURCE.SOURCING 
    SET TAG ENTITY_TYPE = 'SOURCING', SOURCE_SYSTEM = 'SRM', SENSITIVITY = 'RESTRICTED';
ALTER TABLE SUPPLY_CHAIN_FORGE.SRM_SOURCE.SOURCING 
    MODIFY COLUMN CONTRACT_PRICE SET TAG SENSITIVITY = 'RESTRICTED', METRIC_FAMILY = 'COST';

-- WMS_SOURCE
ALTER TABLE SUPPLY_CHAIN_FORGE.WMS_SOURCE.T001W 
    SET TAG ENTITY_TYPE = 'PLANT', SOURCE_SYSTEM = 'WMS', SENSITIVITY = 'INTERNAL';

ALTER TABLE SUPPLY_CHAIN_FORGE.WMS_SOURCE.MARD 
    SET TAG ENTITY_TYPE = 'INVENTORY', SOURCE_SYSTEM = 'WMS', SENSITIVITY = 'INTERNAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.WMS_SOURCE.MARD 
    MODIFY COLUMN LABST SET TAG METRIC_FAMILY = 'INVENTORY';

-- ERP_SOURCE
ALTER TABLE SUPPLY_CHAIN_FORGE.ERP_SOURCE.KNA1 
    SET TAG ENTITY_TYPE = 'CUSTOMER', SOURCE_SYSTEM = 'ERP', SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.ERP_SOURCE.KNA1 
    MODIFY COLUMN NAME1 SET TAG PII = 'TRUE', SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.ERP_SOURCE.KNA1 
    MODIFY COLUMN EMAIL SET TAG PII = 'TRUE', SENSITIVITY = 'CONFIDENTIAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.ERP_SOURCE.KNA1 
    MODIFY COLUMN KLIMK SET TAG SENSITIVITY = 'RESTRICTED';

ALTER TABLE SUPPLY_CHAIN_FORGE.ERP_SOURCE.VBAK 
    SET TAG ENTITY_TYPE = 'ORDER', SOURCE_SYSTEM = 'ERP', SENSITIVITY = 'INTERNAL';

ALTER TABLE SUPPLY_CHAIN_FORGE.ERP_SOURCE.VBAP 
    SET TAG ENTITY_TYPE = 'ORDER_LINE', SOURCE_SYSTEM = 'ERP', SENSITIVITY = 'INTERNAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.ERP_SOURCE.VBAP 
    MODIFY COLUMN QTY_SHIPPED SET TAG METRIC_FAMILY = 'FULFILLMENT';

-- TMS_SOURCE
ALTER TABLE SUPPLY_CHAIN_FORGE.TMS_SOURCE.VTTK 
    SET TAG ENTITY_TYPE = 'SHIPMENT', SOURCE_SYSTEM = 'TMS', SENSITIVITY = 'INTERNAL';
ALTER TABLE SUPPLY_CHAIN_FORGE.TMS_SOURCE.VTTK 
    MODIFY COLUMN PROM_DLV_DT SET TAG METRIC_FAMILY = 'DELIVERY';
ALTER TABLE SUPPLY_CHAIN_FORGE.TMS_SOURCE.VTTK 
    MODIFY COLUMN FREIGHT_AMT SET TAG METRIC_FAMILY = 'COST';
