-- ============================================================
-- policies.sql — Row access policies per persona
-- Owner: CoCo
-- Schema: SUPPLY_CHAIN_FORGE.GOVERNED
-- ============================================================

-- TODO: CoCo will populate using data-governance skill
-- Policies:
--   SUPPLIER_COST_POLICY — Hides cost columns from PLANNER_ROLE
--   CUSTOMER_PII_POLICY — Hides PII from BUYER_ROLE
--   SUPPLIER_FINANCIAL_POLICY — Hides payment terms from LOGISTICS_ROLE
