-- ============================================================
-- tags.sql — Semantic and governance tags
-- Owner: CoCo
-- Schema: SUPPLY_CHAIN_FORGE.GOVERNED
-- ============================================================

-- TODO: CoCo will populate using data-governance skill
-- Expected tags:
--   ENTITY_TYPE (supplier, part, plant, shipment, order, customer, inventory)
--   METRIC_TYPE (otd, fill_rate, doi, landed_cost)
--   SENSITIVITY (public, internal, confidential, restricted)
--   PII (true/false)
