"""Build app/utils/captured.json from CoCo's captured artifacts (C6b).

The app's saved data (mock mode, and a live fallback on the public link) is the last real
Snowflake output CoCo captured, so it is copied here from docs/artifacts. The app can't
read docs/ once deployed (SiS gets only app/). Never edit captured.json by hand: after a
re-capture, run

    .venv/Scripts/python tests/tools/build_captured.py

tests/unit/test_captured.py fails when the file and the artifacts disagree.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ARTIFACTS = ROOT / "docs" / "artifacts"
OUT = ROOT / "app" / "utils" / "captured.json"


def _artifact(name: str) -> dict:
    return json.loads((ARTIFACTS / name).read_text(encoding="utf-8"))


def _source(art: dict, name: str) -> str:
    return f"docs/artifacts/{name} ({art.get('build_step', '?')}, captured {art.get('captured_at') or 'date not recorded'})"


def naive_otd() -> dict:
    """Contract §8's naive ERP-date OTD, measured at the B08c gate (the only capture on the
    current data; art 02 is from the v1 data)."""
    report = (ARTIFACTS / "runs" / "B08c_run.md").read_text(encoding="utf-8")
    value = float(re.search(r"naive \*\*([0-9.]+)\*\*", report).group(1))
    return {"value": value, "source": "docs/artifacts/runs/B08c_run.md (gate 5, the §8 query)"}


def build() -> dict:
    a05, a09, a10 = (_artifact(n) for n in ("05_metric_values.json", "09_consistency_proof.json",
                                              "10_dmf_results.json"))
    p05, p09, p10 = a05["payload"], a09["payload"], a10["payload"]
    health_all = p10["data_health_all"]
    return {
        "_about": "Generated by tests/tools/build_captured.py from docs/artifacts. Do not edit.",
        "metrics": {"source": _source(a05, "05_metric_values.json"), "windows": p05["windows"],
                    "overall": p05["overall"], "by_dimension": p05["by_dimension"]},
        "personas": {"source": _source(a09, "09_consistency_proof.json"),
                     "metrics_by_persona": p09["metrics_by_persona"],
                     "samples_by_persona": p09["samples_by_persona"]},
        "quality": {"source": _source(a10, "10_dmf_results.json"),
                    "dmf_results_latest": p10["dmf_results_latest"],
                    # identical for every role (art 10); one copy is enough
                    "data_health_all": health_all.get("FORGE_ADMIN", next(iter(health_all.values()))),
                    "data_health_shipments": p10["data_health_shipments"]},
        "naive_otd": naive_otd(),
    }


def render(data: dict) -> str:
    return json.dumps(data, sort_keys=True, ensure_ascii=False, separators=(",", ":")) + "\n"


if __name__ == "__main__":
    OUT.write_text(render(build()), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
    sys.exit(0)
