-- ============================================================================
-- data_gen/20_sp_inject_mess.sql — OPS.SP_INJECT_MESS: the §4 defects, on top of a clean load
-- Card:       C08 (.agents/tasks/claude/C08_data_generator.md)
-- Spec:       docs/DATA_SPEC.md §4 (mess catalogue), §3.8 (LOAD_TS cap), §6
-- Role:       ACCOUNTADMIN        Warehouse: FORGE_WH (XS) at SF <= 1
-- Run order:  3 of 5 (00 → 10 → 20 → 30 → 99). Re-runnable: CREATE OR REPLACE.
-- Parameters: TARGET_DB, SEED (the same as the generator's), END_DATE (the same).
-- Expected:   CREATE succeeds. A CALL right after SP_GENERATE_DATA returns
--             {"status": "OK", "injected": {"M01": {"VBAK": n, ...}, ..., "E12": {...}}}.
--             It refuses to run twice on the same load (test customers already present):
--             run SP_GENERATE_DATA first.
--
-- Picks are exact: k = ROUND(rate × base) rows, the k with the lowest
-- HASH(SEED, '<TABLE>', <key>, '<CODE>'), so rates hold even at SF 0.01 and every run
-- picks the same rows. Order of injection (so copies stay identical and no LOAD_TS passes
-- END_DATE 05:00): M04 → E03, E01, E02, E04–E06, E08, E07a–c, E09, E11, E12 → M06 → M02
-- → M03 → M07 → M01. M05 (currencies) is set by the generator, not injected.
-- Deviation (reported in HANDOFF): M07 on VTTK.VBELN uses lower case, because a trailing
-- space doesn't fit VARCHAR(12) on 12-character order IDs. UPPER(TRIM()) repairs both.
-- ============================================================================

CREATE OR REPLACE PROCEDURE SUPPLY_CHAIN_FORGE.OPS.SP_INJECT_MESS(
    TARGET_DB VARCHAR, SEED NUMBER, END_DATE DATE)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
COMMENT = 'C08: injects the DATA_SPEC §4 defects and edge cases into a clean load, with exact, hash-picked counts.'
AS
$$
DECLARE
    stage     VARCHAR DEFAULT 'start';
    run_id    VARCHAR;
    ok_name   BOOLEAN;
    s_date    DATE;
    l_date    DATE;
    cap_ts    TIMESTAMP_NTZ;      -- no LOAD_TS may be later than END_DATE 05:00 (§3.8)
    base      INTEGER;
    k         INTEGER;
    n         INTEGER;
    run_t0    TIMESTAMP_NTZ;
    result    VARIANT;
BEGIN
    SELECT UUID_STRING(), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
           COALESCE(REGEXP_LIKE(:TARGET_DB, '^[A-Za-z_][A-Za-z0-9_$]*$'), FALSE)
      INTO :run_id, :run_t0, :ok_name;
    IF (NOT ok_name OR SEED IS NULL OR END_DATE IS NULL) THEN
        RETURN OBJECT_CONSTRUCT('status', 'ERROR', 'stage', 'parameters',
            'sqlerrm', 'TARGET_DB must be a plain identifier; SEED and END_DATE required');
    END IF;
    EXECUTE IMMEDIATE 'USE SCHEMA ' || :TARGET_DB || '.OPS';
    SELECT DATEADD(year, -10, :END_DATE), DATEADD(day, -1, :END_DATE), TIMESTAMPADD(hour, 5, :END_DATE::TIMESTAMP_NTZ)
      INTO :s_date, :l_date, :cap_ts;

    stage := 'guard';
    SELECT COUNT(*) INTO :n FROM ERP_SOURCE.KNA1 WHERE KUNNR LIKE 'TEST%';
    IF (n > 0) THEN
        RETURN OBJECT_CONSTRUCT('status', 'ERROR', 'stage', 'guard',
            'sqlerrm', 'This load already has injected defects. Run SP_GENERATE_DATA first, then SP_INJECT_MESS once.');
    END IF;

    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_LOG (RUN_ID, TARGET_DB, STAGE, TABLE_NAME, CHUNK, ROWS_WRITTEN, STARTED_AT, ENDED_AT, PARAMS)
    SELECT :run_id, :TARGET_DB, 'start', NULL, NULL, NULL, :run_t0, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
           OBJECT_CONSTRUCT('procedure', 'SP_INJECT_MESS', 'seed', :SEED, 'end_date', :END_DATE);

    -- Daily FX lookup (latest rate on or before each day), for E08's USD threshold.
    CREATE OR REPLACE TEMPORARY TABLE TMP_FX AS
    WITH cal AS (SELECT DATEADD(day, (ROW_NUMBER() OVER (ORDER BY SEQ8()) - 1)::INT, DATEADD(day, -7, :s_date)) AS d
                 FROM TABLE(GENERATOR(ROWCOUNT => 3700))),
    cur AS (SELECT DISTINCT FCURR AS CUR FROM ERP_SOURCE.TCURR),
    grid AS (SELECT c.CUR, cal.d, t.UKURS FROM cal CROSS JOIN cur c
             LEFT JOIN ERP_SOURCE.TCURR t ON t.FCURR = c.CUR AND t.GDATU = cal.d AND t.KURST = 'M' AND t.TCURR = 'USD')
    SELECT CUR, d, LAST_VALUE(UKURS IGNORE NULLS) OVER (PARTITION BY CUR ORDER BY d ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS rate
    FROM grid
    UNION ALL SELECT 'USD', d, 1 FROM cal;

    -- ── M04 test / dummy records ────────────────────────────────────────────
    stage := 'M04';
    INSERT INTO ERP_SOURCE.KNA1 (KUNNR, NAME1, EMAIL, LAND1, REGIO, KTOKD, KLIMK, ERDAT, LOAD_TS)
    SELECT 'TEST' || LPAD(i, 4, '0'), CASE WHEN i = 5 THEN 'DUMMY ACCOUNT' ELSE 'TEST CUSTOMER ' || i END,
           'test' || i || '@example.com', 'USA', 'AMER', 'SMB', 1000, :s_date,
           TIMESTAMPADD(minute, 120, DATEADD(day, 1, :s_date)::TIMESTAMP_NTZ)
    FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ8()) AS i FROM TABLE(GENERATOR(ROWCOUNT => 5)));
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M04', 'KNA1', 5, 1.0, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAK;
    k := ROUND(base * 0.003);
    UPDATE ERP_SOURCE.VBAK t SET KUNNR = p.new_kunnr
    FROM (SELECT VBELN,
                 'TEST' || LPAD(1 + MOD(ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'M04'), VBELN) - 1, 5), 4, '0') AS new_kunnr
          FROM ERP_SOURCE.VBAK
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'M04'), VBELN) <= :k) p
    WHERE t.VBELN = p.VBELN;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M04', 'VBAK', :base, 0.003, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    INSERT INTO SRM_SOURCE.LFA1 (LIFNR, NAME1, LAND1, REGIO, SUPP_TIER, LEAD_TM_DAYS, RELIAB_SCR, ZTERM, EMAIL, ERDAT, LOAD_TS)
    SELECT 'TESTV' || LPAD(i, 3, '0'), 'TEST VENDOR ' || i, 'USA', 'AMER', 3, 30, 0.70, 'NET30',
           'vendor' || i || '@example.com', :s_date, TIMESTAMPADD(minute, 120, DATEADD(day, 1, :s_date)::TIMESTAMP_NTZ)
    FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ8()) AS i FROM TABLE(GENERATOR(ROWCOUNT => 2)));
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M04', 'LFA1', 2, 1.0, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    INSERT INTO SRM_SOURCE.SOURCING (SOURCE_ID, LIFNR, MATNR, IS_PRIMARY, CONTRACT_PRICE, WAERS, VDATU, BDATU, LOAD_TS)
    SELECT 'SRC99000' || i, 'TESTV' || LPAD(i, 3, '0'), m.MATNR, FALSE, 1.00, 'USD', :s_date, NULL,
           TIMESTAMPADD(minute, 120, DATEADD(day, 1, :s_date)::TIMESTAMP_NTZ)
    FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ8()) AS i FROM TABLE(GENERATOR(ROWCOUNT => 2))) g
    JOIN (SELECT MATNR, ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'SOURCING', MATNR, 'M04'), MATNR) AS r
          FROM SRM_SOURCE.MARA) m ON m.r = g.i;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M04', 'SOURCING', 2, 1.0, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    INSERT INTO SRM_SOURCE.MARA (MATNR, MAKTX, MATKL, SUBCAT, STPRS, BRGEW, CRIT_FLG, LOAD_TS)
    SELECT 'MAT99990' || i, 'DO NOT USE - TEST PART', 'FASTENERS', 'SCREWS', 0.01, 0.001, FALSE,
           TIMESTAMPADD(minute, 120, DATEADD(day, 1, :s_date)::TIMESTAMP_NTZ)
    FROM (SELECT ROW_NUMBER() OVER (ORDER BY SEQ8()) AS i FROM TABLE(GENERATOR(ROWCOUNT => 4)));
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M04', 'MARA', 4, 1.0, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAP;
    k := ROUND(base * 0.001);
    UPDATE ERP_SOURCE.VBAP t SET MATNR = p.new_matnr
    FROM (SELECT LINE_ID,
                 'MAT99990' || (1 + MOD(ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'M04'), LINE_ID) - 1, 4)) AS new_matnr
          FROM ERP_SOURCE.VBAP
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'M04'), LINE_ID) <= :k) p
    WHERE t.LINE_ID = p.LINE_ID;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M04', 'VBAP', :base, 0.001, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E03 return orders (1.5% of orders; 60% of them with a return shipment) ─
    stage := 'E03';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAK;
    k := ROUND(base * 0.015);
    UPDATE ERP_SOURCE.VBAK t SET AUART = 'RE'
    FROM (SELECT VBELN FROM ERP_SOURCE.VBAK
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'E03'), VBELN) <= :k) p
    WHERE t.VBELN = p.VBELN;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E03', 'VBAK', :base, 0.015, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- Keep a shipment on 60% of the returns: remove the shipments of the excess.
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAK WHERE AUART = 'RE';
    SELECT GREATEST(0, COUNT(DISTINCT o.VBELN) - ROUND(:base * 0.60)) INTO :k
    FROM ERP_SOURCE.VBAK o JOIN TMS_SOURCE.VTTK s ON s.VBELN = o.VBELN WHERE o.AUART = 'RE';
    DELETE FROM TMS_SOURCE.VTTK t
    USING (SELECT o.VBELN FROM ERP_SOURCE.VBAK o
           WHERE o.AUART = 'RE' AND EXISTS (SELECT 1 FROM TMS_SOURCE.VTTK s WHERE s.VBELN = o.VBELN)
           QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', o.VBELN, 'E03ship'), o.VBELN) <= :k) p
    WHERE t.VBELN = p.VBELN;
    SELECT COUNT(DISTINCT o.VBELN) INTO :n
    FROM ERP_SOURCE.VBAK o JOIN TMS_SOURCE.VTTK s ON s.VBELN = o.VBELN WHERE o.AUART = 'RE';
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E03', 'VTTK_SHARE', :base, 0.60, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E01 missing promised date (0.8% of delivered shipments) ─────────────
    stage := 'E01';
    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK WHERE ACT_DLV_DT IS NOT NULL;
    k := ROUND(base * 0.008);
    UPDATE TMS_SOURCE.VTTK t SET PROM_DLV_DT = NULL
    FROM (SELECT TKNUM FROM TMS_SOURCE.VTTK WHERE ACT_DLV_DT IS NOT NULL
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'E01'), TKNUM) <= :k) p
    WHERE t.TKNUM = p.TKNUM;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E01', 'VTTK', :base, 0.008, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E02 cancelled after shipping (0.5% of DELIVERED orders) ─────────────
    stage := 'E02';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAK WHERE GBSTK = 'DELIVERED' AND AUART = 'OR';
    k := ROUND(base * 0.005);
    UPDATE ERP_SOURCE.VBAK t SET GBSTK = 'CANCELLED'
    FROM (SELECT VBELN FROM ERP_SOURCE.VBAK WHERE GBSTK = 'DELIVERED' AND AUART = 'OR'
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'E02'), VBELN) <= :k) p
    WHERE t.VBELN = p.VBELN;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E02', 'VBAK', :base, 0.005, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E04 over-shipment (1% of shipped lines) ─────────────────────────────
    stage := 'E04';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAP WHERE QTY_SHIPPED > 0;
    k := ROUND(base * 0.01);
    UPDATE ERP_SOURCE.VBAP t
       SET QTY_SHIPPED = ROUND(t.KWMENG * (1.05 + 0.15 * BITAND(HASH(:SEED, 'VBAP', t.LINE_ID, 'E04q'), 4294967295) / 4294967295.0))
    FROM (SELECT LINE_ID FROM ERP_SOURCE.VBAP WHERE QTY_SHIPPED > 0
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'E04'), LINE_ID) <= :k) p
    WHERE t.LINE_ID = p.LINE_ID;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E04', 'VBAP', :base, 0.01, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E06 zero daily usage (2% of stocked pairs, all their snapshots) ─────
    stage := 'E06';
    SELECT COUNT(*) INTO :base FROM (SELECT DISTINCT WERKS, MATNR FROM WMS_SOURCE.MARD);
    k := ROUND(base * 0.02);
    UPDATE WMS_SOURCE.MARD t
       SET DAILY_USG = 0, REORD_PT = 0,
           LABST = 50 + FLOOR(451 * BITAND(HASH(:SEED, 'MARD', t.INV_KEY, 'E06q'), 4294967295) / 4294967295.0)
    FROM (SELECT WERKS, MATNR FROM (SELECT DISTINCT WERKS, MATNR FROM WMS_SOURCE.MARD)
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'MARD', WERKS || '-' || MATNR, 'E06'), WERKS, MATNR) <= :k) p
    WHERE t.WERKS = p.WERKS AND t.MATNR = p.MATNR;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E06', 'MARD_PAIRS', :base, 0.02, :k, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E05 negative on-hand (0.3% of snapshot rows) ────────────────────────
    stage := 'E05';
    SELECT COUNT(*) INTO :base FROM WMS_SOURCE.MARD;
    k := ROUND(base * 0.003);
    UPDATE WMS_SOURCE.MARD t
       SET LABST = -(1 + FLOOR(50 * BITAND(HASH(:SEED, 'MARD', t.INV_KEY, 'E05q'), 4294967295) / 4294967295.0))
    FROM (SELECT INV_KEY FROM WMS_SOURCE.MARD
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'MARD', INV_KEY, 'E05'), INV_KEY) <= :k) p
    WHERE t.INV_KEY = p.INV_KEY;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E05', 'MARD', :base, 0.003, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E08 cost outliers (0.1% of shipments, among those with freight ≥ USD 300) ─
    stage := 'E08';
    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK;
    k := ROUND(base * 0.001);
    UPDATE TMS_SOURCE.VTTK t SET FREIGHT_AMT = t.FREIGHT_AMT * 100
    FROM (SELECT s.TKNUM FROM TMS_SOURCE.VTTK s JOIN TMP_FX fx ON fx.CUR = s.WAERS AND fx.d = s.DPTBG
          WHERE s.FREIGHT_AMT * fx.rate >= 300
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', s.TKNUM, 'E08'), s.TKNUM) <= :k) p
    WHERE t.TKNUM = p.TKNUM;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E08', 'VTTK', :base, 0.001, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E07a/b/c NULL duty (60% of domestic), handling (1%), freight (0.2%) ─
    stage := 'E07';
    SELECT COUNT(*) INTO :base
    FROM TMS_SOURCE.VTTK s JOIN ERP_SOURCE.VBAK o ON o.VBELN = s.VBELN
    JOIN ERP_SOURCE.KNA1 c ON c.KUNNR = o.KUNNR JOIN WMS_SOURCE.T001W pl ON pl.WERKS = s.WERKS
    WHERE pl.LAND1 = c.LAND1;
    k := ROUND(base * 0.60);
    UPDATE TMS_SOURCE.VTTK t SET DUTY_AMT = NULL
    FROM (SELECT s.TKNUM FROM TMS_SOURCE.VTTK s JOIN ERP_SOURCE.VBAK o ON o.VBELN = s.VBELN
          JOIN ERP_SOURCE.KNA1 c ON c.KUNNR = o.KUNNR JOIN WMS_SOURCE.T001W pl ON pl.WERKS = s.WERKS
          WHERE pl.LAND1 = c.LAND1
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', s.TKNUM, 'E07a'), s.TKNUM) <= :k) p
    WHERE t.TKNUM = p.TKNUM;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E07a', 'VTTK', :base, 0.60, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK;
    k := ROUND(base * 0.01);
    UPDATE TMS_SOURCE.VTTK t SET HANDLING_AMT = NULL
    FROM (SELECT TKNUM FROM TMS_SOURCE.VTTK
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'E07b'), TKNUM) <= :k) p
    WHERE t.TKNUM = p.TKNUM;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E07b', 'VTTK', :base, 0.01, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    k := ROUND(base * 0.002);
    UPDATE TMS_SOURCE.VTTK t SET FREIGHT_AMT = NULL
    FROM (SELECT TKNUM FROM TMS_SOURCE.VTTK
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'E07c'), TKNUM) <= :k) p
    WHERE t.TKNUM = p.TKNUM;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E07c', 'VTTK', :base, 0.002, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E09a/b orphan lines and shipments (0.2% each): an order that doesn't exist ─
    stage := 'E09';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAP;
    k := ROUND(base * 0.002);
    UPDATE ERP_SOURCE.VBAP t SET VBELN = p.new_vbeln
    FROM (SELECT LINE_ID, 'ORD9' || LPAD(ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'E09a'), LINE_ID), 8, '0') AS new_vbeln
          FROM ERP_SOURCE.VBAP
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'E09a'), LINE_ID) <= :k) p
    WHERE t.LINE_ID = p.LINE_ID;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E09a', 'VBAP', :base, 0.002, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK;
    k := ROUND(base * 0.002);
    UPDATE TMS_SOURCE.VTTK t SET VBELN = p.new_vbeln
    FROM (SELECT TKNUM, 'ORD9' || LPAD(50000000 + ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'E09b'), TKNUM), 8, '0') AS new_vbeln
          FROM TMS_SOURCE.VTTK
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'E09b'), TKNUM) <= :k) p
    WHERE t.TKNUM = p.TKNUM;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E09b', 'VTTK', :base, 0.002, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E11 two valid primaries (1% of parts): a second, later primary row ───
    stage := 'E11';
    SELECT COUNT(*) INTO :base FROM SRM_SOURCE.MARA WHERE MATNR NOT LIKE 'MAT9999%';
    k := ROUND(base * 0.01);
    INSERT INTO SRM_SOURCE.SOURCING (SOURCE_ID, LIFNR, MATNR, IS_PRIMARY, CONTRACT_PRICE, WAERS, VDATU, BDATU, LOAD_TS)
    WITH cur AS (   -- the primary valid today, per part
        SELECT s.* FROM SRM_SOURCE.SOURCING s
        WHERE s.IS_PRIMARY AND s.BDATU IS NULL AND s.MATNR NOT LIKE 'MAT9999%'
        QUALIFY ROW_NUMBER() OVER (PARTITION BY s.MATNR ORDER BY s.VDATU DESC, s.SOURCE_ID) = 1),
    pick AS (
        SELECT cur.*, ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'SOURCING', cur.MATNR, 'E11'), cur.MATNR) AS r
        FROM cur QUALIFY r <= :k),
    d AS (
        SELECT pick.*,
               LEAST(DATEADD(day, -1, :l_date),
                     DATEADD(day, (30 + FLOOR(335 * BITAND(HASH(:SEED, 'SOURCING', pick.MATNR, 'E11d'), 4294967295) / 4294967295.0))::INT,
                             pick.VDATU)) AS new_vdatu
        FROM pick)
    SELECT 'SRC9' || LPAD(d.r, 5, '0'),
           'SUP' || LPAD(1 + MOD(SUBSTR(d.LIFNR, 4)::NUMBER + 36, 150), 5, '0'),
           d.MATNR, TRUE, d.CONTRACT_PRICE, d.WAERS, d.new_vdatu, NULL,
           TIMESTAMPADD(minute, 120, DATEADD(day, 1, d.new_vdatu)::TIMESTAMP_NTZ)
    FROM d;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E11', 'SOURCING', :base, 0.01, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── E12 future-dated orders (0.02% of orders, among those without shipments) ─
    stage := 'E12';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAK;
    k := ROUND(base * 0.0002);
    UPDATE ERP_SOURCE.VBAK t
       SET AUDAT = DATEADD(day, (1 + FLOOR(400 * BITAND(HASH(:SEED, 'VBAK', t.VBELN, 'E12d'), 4294967295) / 4294967295.0))::INT,
                           t.LOAD_TS::DATE)
    FROM (SELECT o.VBELN FROM ERP_SOURCE.VBAK o
          WHERE o.AUART = 'OR' AND NOT EXISTS (SELECT 1 FROM TMS_SOURCE.VTTK s WHERE s.VBELN = o.VBELN)
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', o.VBELN, 'E12'), o.VBELN) <= :k) p
    WHERE t.VBELN = p.VBELN;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'E12', 'VBAK', :base, 0.0002, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── M06 late-arriving rows (1% of VBAP and VTTK rows at least 30 days old) ─
    -- The business date is LOAD_TS's day minus one (§3.8), before any shift.
    stage := 'M06';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAP WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -30, :l_date);
    k := ROUND(base * 0.01);
    UPDATE ERP_SOURCE.VBAP t
       SET LOAD_TS = TIMESTAMPADD(minute, (120 + FLOOR(181 * BITAND(HASH(:SEED, 'VBAP', t.LINE_ID, 'M06t'), 4294967295) / 4294967295.0))::INT,
                     DATEADD(day, (3 + FLOOR(28 * BITAND(HASH(:SEED, 'VBAP', t.LINE_ID, 'M06d'), 4294967295) / 4294967295.0))::INT,
                             DATEADD(day, -1, t.LOAD_TS::DATE))::TIMESTAMP_NTZ)
    FROM (SELECT LINE_ID FROM ERP_SOURCE.VBAP WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -30, :l_date)
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'M06'), LINE_ID) <= :k) p
    WHERE t.LINE_ID = p.LINE_ID;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M06', 'VBAP', :base, 0.01, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -30, :l_date);
    k := ROUND(base * 0.01);
    UPDATE TMS_SOURCE.VTTK t
       SET LOAD_TS = TIMESTAMPADD(minute, (120 + FLOOR(181 * BITAND(HASH(:SEED, 'VTTK', t.TKNUM, 'M06t'), 4294967295) / 4294967295.0))::INT,
                     DATEADD(day, (3 + FLOOR(28 * BITAND(HASH(:SEED, 'VTTK', t.TKNUM, 'M06d'), 4294967295) / 4294967295.0))::INT,
                             DATEADD(day, -1, t.LOAD_TS::DATE))::TIMESTAMP_NTZ)
    FROM (SELECT TKNUM FROM TMS_SOURCE.VTTK WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -30, :l_date)
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'M06'), TKNUM) <= :k) p
    WHERE t.TKNUM = p.TKNUM;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M06', 'VTTK', :base, 0.01, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── M02 status-update versions: an older copy with the earlier state ────
    stage := 'M02';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAK WHERE GBSTK IN ('SHIPPED', 'DELIVERED');
    k := ROUND(base * 0.10);
    INSERT INTO ERP_SOURCE.VBAK (VBELN, KUNNR, AUDAT, ERDAT, GBSTK, PRIO, AUART, WAERK, LOAD_TS)
    SELECT VBELN, KUNNR, AUDAT, ERDAT, 'OPEN', PRIO, AUART, WAERK,
           TIMESTAMPADD(minute, (120 + FLOOR(181 * BITAND(HASH(:SEED, 'VBAK', VBELN, 'M02t'), 4294967295) / 4294967295.0))::INT,
                        DATEADD(day, 1, AUDAT)::TIMESTAMP_NTZ)
    FROM ERP_SOURCE.VBAK WHERE GBSTK IN ('SHIPPED', 'DELIVERED')
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'M02'), VBELN) <= :k;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M02', 'VBAK', :base, 0.10, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK WHERE ACT_DLV_DT IS NOT NULL;
    k := ROUND(base * 0.08);
    INSERT INTO TMS_SOURCE.VTTK (TKNUM, VBELN, WERKS, CARRIER_CD, DPTBG, PROM_DLV_DT, ACT_DLV_DT,
                                 FREIGHT_AMT, DUTY_AMT, HANDLING_AMT, SHP_STATUS, WAERS, LOAD_TS)
    SELECT TKNUM, VBELN, WERKS, CARRIER_CD, DPTBG, PROM_DLV_DT, NULL, FREIGHT_AMT, DUTY_AMT, HANDLING_AMT,
           'IN_TRANSIT', WAERS,
           TIMESTAMPADD(minute, (120 + FLOOR(181 * BITAND(HASH(:SEED, 'VTTK', TKNUM, 'M02t'), 4294967295) / 4294967295.0))::INT,
                        DATEADD(day, 1, DPTBG)::TIMESTAMP_NTZ)
    FROM TMS_SOURCE.VTTK WHERE ACT_DLV_DT IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'M02'), TKNUM) <= :k;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M02', 'VTTK', :base, 0.08, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── M03 code variants: only the §4.3 variants, picked uniformly ─────────
    stage := 'M03';
    -- The §4.3 variants, '|'-separated (spaces are part of some variants and are kept).
    CREATE OR REPLACE TEMPORARY TABLE TMP_VAR AS
    SELECT v.DOMAIN, v.CANONICAL, f.value::VARCHAR AS VARIANT, f.index AS IDX,
           COUNT(*) OVER (PARTITION BY v.DOMAIN, v.CANONICAL) AS CNT
    FROM (VALUES
        ('REGION', 'APAC', 'Apac|apac |ASIA-PAC|Asia Pacific'),
        ('REGION', 'EMEA', 'emea| EMEA|Europe|EU'),
        ('REGION', 'AMER', 'Amer|NA|North America|Americas'),
        ('ORDER_STATUS', 'OPEN', 'Open|OPN'),
        ('ORDER_STATUS', 'SHIPPED', 'Shipped|SHP'),
        ('ORDER_STATUS', 'DELIVERED', 'Delivered|DLV|delivered '),
        ('ORDER_STATUS', 'CANCELLED', 'Cancelled|CANCELED|CNL'),
        ('PRIORITY', 'HIGH', 'High|H|URGENT'),
        ('PRIORITY', 'NORMAL', 'Normal|MED|MEDIUM'),
        ('PRIORITY', 'LOW', 'Low|L'),
        ('SHIPMENT_STATUS', 'IN_TRANSIT', 'In Transit|IN-TRANSIT|INTRANSIT'),
        ('SHIPMENT_STATUS', 'DELIVERED', 'Delivered|DLV'),
        ('SHIPMENT_STATUS', 'DELAYED', 'Delayed|LATE'),
        ('CARRIER', 'DHL_EXPRESS', 'DHL|DHL Express|dhl_express'),
        ('CARRIER', 'FEDEX_FREIGHT', 'FedEx|FEDEX FREIGHT'),
        ('CARRIER', 'MAERSK_LOGISTICS', 'Maersk|MAERSK'),
        ('CARRIER', 'KUEHNE_NAGEL', 'K+N|Kuehne+Nagel|KUEHNE + NAGEL'),
        ('CARRIER', 'DB_SCHENKER', 'DB Schenker|SCHENKER'),
        ('CARRIER', 'UPS_SUPPLY_CHAIN', 'UPS|UPS SCS'),
        ('CARRIER', 'XPO_LOGISTICS', 'XPO'),
        ('CARRIER', 'CEVA_LOGISTICS', 'CEVA'),
        ('CARRIER', 'FLEXPORT', 'Flexport'),
        ('CATEGORY', 'ELECTRONICS', 'Electronics|ELECTRONIC'),
        ('CATEGORY', 'MECHANICAL', 'Mechanical|MECH'),
        ('CATEGORY', 'RAW_MATERIAL', 'RAW MATERIAL|Raw-Material|RAW_MATERIALS'),
        ('CATEGORY', 'PACKAGING', 'Packaging|PKG'),
        ('CATEGORY', 'CHEMICAL', 'Chemical|CHEMICALS'),
        ('CATEGORY', 'FASTENERS', 'Fasteners |FASTENER'),
        ('SEGMENT', 'ENTERPRISE', 'Enterprise|ENT'),
        ('SEGMENT', 'MIDMARKET', 'MID-MARKET|Mid Market|MM'),
        ('SEGMENT', 'SMB', 'Small Business|smb')
    ) AS v(DOMAIN, CANONICAL, LIST),
    LATERAL SPLIT_TO_TABLE(v.LIST, '|') f;

    -- LFA1.REGIO 8%
    SELECT COUNT(*) INTO :base FROM SRM_SOURCE.LFA1;
    k := ROUND(base * 0.08);
    UPDATE SRM_SOURCE.LFA1 t SET REGIO = v.VARIANT
    FROM (SELECT LIFNR, REGIO AS canon, BITAND(HASH(:SEED, 'LFA1', LIFNR, 'M03v'), 4294967295) / 4294967295.0 AS u
          FROM SRM_SOURCE.LFA1 QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'LFA1', LIFNR, 'M03'), LIFNR) <= :k) p, TMP_VAR v
    WHERE t.LIFNR = p.LIFNR AND v.DOMAIN = 'REGION' AND v.CANONICAL = p.canon AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'LFA1.REGIO', :base, 0.08, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- KNA1.REGIO 8%
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.KNA1;
    k := ROUND(base * 0.08);
    UPDATE ERP_SOURCE.KNA1 t SET REGIO = v.VARIANT
    FROM (SELECT KUNNR, REGIO AS canon, BITAND(HASH(:SEED, 'KNA1', KUNNR, 'M03v'), 4294967295) / 4294967295.0 AS u
          FROM ERP_SOURCE.KNA1 QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'KNA1', KUNNR, 'M03'), KUNNR) <= :k) p, TMP_VAR v
    WHERE t.KUNNR = p.KUNNR AND v.DOMAIN = 'REGION' AND v.CANONICAL = p.canon AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'KNA1.REGIO', :base, 0.08, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- KNA1.KTOKD 3%
    k := ROUND(base * 0.03);
    UPDATE ERP_SOURCE.KNA1 t SET KTOKD = v.VARIANT
    FROM (SELECT KUNNR, KTOKD AS canon, BITAND(HASH(:SEED, 'KNA1', KUNNR, 'M03sv'), 4294967295) / 4294967295.0 AS u
          FROM ERP_SOURCE.KNA1 QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'KNA1', KUNNR, 'M03s'), KUNNR) <= :k) p, TMP_VAR v
    WHERE t.KUNNR = p.KUNNR AND v.DOMAIN = 'SEGMENT' AND v.CANONICAL = p.canon AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'KNA1.KTOKD', :base, 0.03, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- T001W.REGION_CD: PL03 and PL11 only
    UPDATE WMS_SOURCE.T001W t SET REGION_CD = v.VARIANT
    FROM TMP_VAR v
    WHERE t.WERKS IN ('PL03', 'PL11') AND v.DOMAIN = 'REGION' AND v.CANONICAL = t.REGION_CD
      AND v.IDX = LEAST(v.CNT, 1 + FLOOR(v.CNT * BITAND(HASH(:SEED, 'T001W', t.WERKS, 'M03v'), 4294967295) / 4294967295.0))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'T001W.REGION_CD', 12, 2 / 12, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- MARA.MATKL 5%
    SELECT COUNT(*) INTO :base FROM SRM_SOURCE.MARA;
    k := ROUND(base * 0.05);
    UPDATE SRM_SOURCE.MARA t SET MATKL = v.VARIANT
    FROM (SELECT MATNR, MATKL AS canon, BITAND(HASH(:SEED, 'MARA', MATNR, 'M03v'), 4294967295) / 4294967295.0 AS u
          FROM SRM_SOURCE.MARA QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'MARA', MATNR, 'M03'), MATNR) <= :k) p, TMP_VAR v
    WHERE t.MATNR = p.MATNR AND v.DOMAIN = 'CATEGORY' AND v.CANONICAL = p.canon AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'MARA.MATKL', :base, 0.05, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- VBAK.GBSTK 3% and VBAK.PRIO 2% (row identity: key + LOAD_TS, since M02 copies exist)
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAK;
    k := ROUND(base * 0.03);
    UPDATE ERP_SOURCE.VBAK t SET GBSTK = v.VARIANT
    FROM (SELECT VBELN, LOAD_TS AS lts, GBSTK AS canon, BITAND(HASH(:SEED, 'VBAK', VBELN, 'M03gv'), 4294967295) / 4294967295.0 AS u
          FROM ERP_SOURCE.VBAK QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'M03g'), VBELN, LOAD_TS) <= :k) p, TMP_VAR v
    WHERE t.VBELN = p.VBELN AND t.LOAD_TS = p.lts AND v.DOMAIN = 'ORDER_STATUS' AND v.CANONICAL = p.canon
      AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'VBAK.GBSTK', :base, 0.03, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    k := ROUND(base * 0.02);
    UPDATE ERP_SOURCE.VBAK t SET PRIO = v.VARIANT
    FROM (SELECT VBELN, LOAD_TS AS lts, PRIO AS canon, BITAND(HASH(:SEED, 'VBAK', VBELN, 'M03pv'), 4294967295) / 4294967295.0 AS u
          FROM ERP_SOURCE.VBAK QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'M03p'), VBELN, LOAD_TS) <= :k) p, TMP_VAR v
    WHERE t.VBELN = p.VBELN AND t.LOAD_TS = p.lts AND v.DOMAIN = 'PRIORITY' AND v.CANONICAL = p.canon
      AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'VBAK.PRIO', :base, 0.02, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- VTTK.SHP_STATUS 3% and VTTK.CARRIER_CD 6%
    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK;
    k := ROUND(base * 0.03);
    UPDATE TMS_SOURCE.VTTK t SET SHP_STATUS = v.VARIANT
    FROM (SELECT TKNUM, LOAD_TS AS lts, SHP_STATUS AS canon, BITAND(HASH(:SEED, 'VTTK', TKNUM, 'M03sv'), 4294967295) / 4294967295.0 AS u
          FROM TMS_SOURCE.VTTK QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'M03s'), TKNUM, LOAD_TS) <= :k) p, TMP_VAR v
    WHERE t.TKNUM = p.TKNUM AND t.LOAD_TS = p.lts AND v.DOMAIN = 'SHIPMENT_STATUS' AND v.CANONICAL = p.canon
      AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'VTTK.SHP_STATUS', :base, 0.03, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    k := ROUND(base * 0.06);
    UPDATE TMS_SOURCE.VTTK t SET CARRIER_CD = v.VARIANT
    FROM (SELECT TKNUM, LOAD_TS AS lts, CARRIER_CD AS canon, BITAND(HASH(:SEED, 'VTTK', TKNUM, 'M03cv'), 4294967295) / 4294967295.0 AS u
          FROM TMS_SOURCE.VTTK QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'M03c'), TKNUM, LOAD_TS) <= :k) p, TMP_VAR v
    WHERE t.TKNUM = p.TKNUM AND t.LOAD_TS = p.lts AND v.DOMAIN = 'CARRIER' AND v.CANONICAL = p.canon
      AND v.IDX = LEAST(v.CNT, 1 + FLOOR(p.u * v.CNT))::INT;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M03', 'VTTK.CARRIER_CD', :base, 0.06, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── M07 ID whitespace / case ────────────────────────────────────────────
    stage := 'M07';
    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAP;
    k := ROUND(base * 0.005);
    UPDATE ERP_SOURCE.VBAP t
       SET MATNR = CASE WHEN BITAND(HASH(:SEED, 'VBAP', t.LINE_ID, 'M07m'), 4294967295) / 4294967295.0 < 0.5
                        THEN ' ' || t.MATNR ELSE LOWER(t.MATNR) END
    FROM (SELECT LINE_ID FROM ERP_SOURCE.VBAP
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'M07'), LINE_ID) <= :k) p
    WHERE t.LINE_ID = p.LINE_ID;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M07', 'VBAP.MATNR', :base, 0.005, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    k := ROUND(base * 0.002);
    UPDATE ERP_SOURCE.VBAP t SET VBELN = LOWER(t.VBELN)
    FROM (SELECT LINE_ID FROM ERP_SOURCE.VBAP
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'M07v'), LINE_ID) <= :k) p
    WHERE t.LINE_ID = p.LINE_ID;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M07', 'VBAP.VBELN', :base, 0.002, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM TMS_SOURCE.VTTK;
    k := ROUND(base * 0.003);
    UPDATE TMS_SOURCE.VTTK t SET VBELN = LOWER(t.VBELN)   -- spec: trailing space; doesn't fit VARCHAR(12)
    FROM (SELECT TKNUM, LOAD_TS AS lts FROM TMS_SOURCE.VTTK
          QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'M07'), TKNUM, LOAD_TS) <= :k) p
    WHERE t.TKNUM = p.TKNUM AND t.LOAD_TS = p.lts;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M07', 'VTTK.VBELN', :base, 0.003, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── M01 re-sent duplicates (last): an identical copy, LOAD_TS + 1-5 days ──
    -- Only the latest version of a key is copied, only rows whose business date is at
    -- least 5 days old, and only if the copy stays within the END_DATE 05:00 cap.
    stage := 'M01';
    SELECT COUNT(*) INTO :base
    FROM (SELECT LOAD_TS FROM ERP_SOURCE.VBAK QUALIFY ROW_NUMBER() OVER (PARTITION BY VBELN ORDER BY LOAD_TS DESC) = 1)
    WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date);
    k := ROUND(base * 0.02);
    INSERT INTO ERP_SOURCE.VBAK (VBELN, KUNNR, AUDAT, ERDAT, GBSTK, PRIO, AUART, WAERK, LOAD_TS)
    WITH c AS (
        SELECT v.*, 1 + FLOOR(5 * BITAND(HASH(:SEED, 'VBAK', v.VBELN, 'M01d'), 4294967295) / 4294967295.0) AS off
        FROM ERP_SOURCE.VBAK v
        QUALIFY ROW_NUMBER() OVER (PARTITION BY v.VBELN ORDER BY v.LOAD_TS DESC) = 1)
    SELECT VBELN, KUNNR, AUDAT, ERDAT, GBSTK, PRIO, AUART, WAERK, TIMESTAMPADD(day, off, LOAD_TS)
    FROM c
    WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date) AND TIMESTAMPADD(day, off, LOAD_TS) <= :cap_ts
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAK', VBELN, 'M01'), VBELN) <= :k;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M01', 'VBAK', :base, 0.02, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.VBAP WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date);
    k := ROUND(base * 0.015);
    INSERT INTO ERP_SOURCE.VBAP (LINE_ID, VBELN, MATNR, WERKS, KWMENG, QTY_SHIPPED, NETPR, LOAD_TS)
    WITH c AS (
        SELECT v.*, 1 + FLOOR(5 * BITAND(HASH(:SEED, 'VBAP', v.LINE_ID, 'M01d'), 4294967295) / 4294967295.0) AS off
        FROM ERP_SOURCE.VBAP v)
    SELECT LINE_ID, VBELN, MATNR, WERKS, KWMENG, QTY_SHIPPED, NETPR, TIMESTAMPADD(day, off, LOAD_TS)
    FROM c
    WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date) AND TIMESTAMPADD(day, off, LOAD_TS) <= :cap_ts
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VBAP', LINE_ID, 'M01'), LINE_ID) <= :k;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M01', 'VBAP', :base, 0.015, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base
    FROM (SELECT LOAD_TS FROM TMS_SOURCE.VTTK QUALIFY ROW_NUMBER() OVER (PARTITION BY TKNUM ORDER BY LOAD_TS DESC) = 1)
    WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date);
    k := ROUND(base * 0.03);
    INSERT INTO TMS_SOURCE.VTTK (TKNUM, VBELN, WERKS, CARRIER_CD, DPTBG, PROM_DLV_DT, ACT_DLV_DT,
                                 FREIGHT_AMT, DUTY_AMT, HANDLING_AMT, SHP_STATUS, WAERS, LOAD_TS)
    WITH c AS (
        SELECT v.*, 1 + FLOOR(5 * BITAND(HASH(:SEED, 'VTTK', v.TKNUM, 'M01d'), 4294967295) / 4294967295.0) AS off
        FROM TMS_SOURCE.VTTK v
        QUALIFY ROW_NUMBER() OVER (PARTITION BY v.TKNUM ORDER BY v.LOAD_TS DESC) = 1)
    SELECT TKNUM, VBELN, WERKS, CARRIER_CD, DPTBG, PROM_DLV_DT, ACT_DLV_DT, FREIGHT_AMT, DUTY_AMT, HANDLING_AMT,
           SHP_STATUS, WAERS, TIMESTAMPADD(day, off, LOAD_TS)
    FROM c
    WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date) AND TIMESTAMPADD(day, off, LOAD_TS) <= :cap_ts
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'VTTK', TKNUM, 'M01'), TKNUM) <= :k;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M01', 'VTTK', :base, 0.03, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM WMS_SOURCE.MARD WHERE SNAP_DT <= DATEADD(day, -5, :l_date);
    k := ROUND(base * 0.005);
    INSERT INTO WMS_SOURCE.MARD (INV_KEY, WERKS, MATNR, LABST, INSME, REORD_PT, DAILY_USG, SNAP_DT, LOAD_TS)
    WITH c AS (
        SELECT v.*, 1 + FLOOR(5 * BITAND(HASH(:SEED, 'MARD', v.INV_KEY, 'M01d'), 4294967295) / 4294967295.0) AS off
        FROM WMS_SOURCE.MARD v)
    SELECT INV_KEY, WERKS, MATNR, LABST, INSME, REORD_PT, DAILY_USG, SNAP_DT, TIMESTAMPADD(day, off, LOAD_TS)
    FROM c
    WHERE SNAP_DT <= DATEADD(day, -5, :l_date) AND TIMESTAMPADD(day, off, LOAD_TS) <= :cap_ts
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'MARD', INV_KEY, 'M01'), INV_KEY) <= :k;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M01', 'MARD', :base, 0.005, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    SELECT COUNT(*) INTO :base FROM ERP_SOURCE.KNA1
    WHERE KUNNR NOT LIKE 'TEST%' AND DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date);
    k := ROUND(base * 0.01);
    INSERT INTO ERP_SOURCE.KNA1 (KUNNR, NAME1, EMAIL, LAND1, REGIO, KTOKD, KLIMK, ERDAT, LOAD_TS)
    WITH c AS (
        SELECT v.*, 1 + FLOOR(5 * BITAND(HASH(:SEED, 'KNA1', v.KUNNR, 'M01d'), 4294967295) / 4294967295.0) AS off
        FROM ERP_SOURCE.KNA1 v WHERE v.KUNNR NOT LIKE 'TEST%')
    SELECT KUNNR, NAME1, EMAIL, LAND1, REGIO, KTOKD, KLIMK, ERDAT, TIMESTAMPADD(day, off, LOAD_TS)
    FROM c
    WHERE DATEADD(day, -1, LOAD_TS::DATE) <= DATEADD(day, -5, :l_date) AND TIMESTAMPADD(day, off, LOAD_TS) <= :cap_ts
    QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(:SEED, 'KNA1', KUNNR, 'M01'), KUNNR) <= :k;
    n := SQLROWCOUNT;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG SELECT :run_id, :TARGET_DB, 'M01', 'KNA1', :base, 0.01, :n, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;

    -- ── Messy-load facts and the result ─────────────────────────────────────
    stage := 'stats';
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_STATS (RUN_ID, TARGET_DB, PHASE, NAME, TABLE_NAME, VALUE, DETAIL, PARAMS, LOGGED_AT)
    WITH x AS (
        SELECT 'T001W' AS t, COUNT(*) AS n, TO_VARCHAR(HASH_AGG(*)) AS h FROM WMS_SOURCE.T001W
        UNION ALL SELECT 'LFA1', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM SRM_SOURCE.LFA1
        UNION ALL SELECT 'MARA', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM SRM_SOURCE.MARA
        UNION ALL SELECT 'KNA1', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM ERP_SOURCE.KNA1
        UNION ALL SELECT 'TCURR', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM ERP_SOURCE.TCURR
        UNION ALL SELECT 'SOURCING', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM SRM_SOURCE.SOURCING
        UNION ALL SELECT 'VBAK', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM ERP_SOURCE.VBAK
        UNION ALL SELECT 'VBAP', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM ERP_SOURCE.VBAP
        UNION ALL SELECT 'VTTK', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM TMS_SOURCE.VTTK
        UNION ALL SELECT 'MARD', COUNT(*), TO_VARCHAR(HASH_AGG(*)) FROM WMS_SOURCE.MARD)
    SELECT :run_id, :TARGET_DB, 'MESSY', 'ROWS', t, n::FLOAT, NULL,
           OBJECT_CONSTRUCT('seed', :SEED, 'end_date', :END_DATE), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ FROM x
    UNION ALL
    SELECT :run_id, :TARGET_DB, 'MESSY', 'CHECKSUM', t, NULL, h,
           OBJECT_CONSTRUCT('seed', :SEED, 'end_date', :END_DATE), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ FROM x;

    SELECT OBJECT_CONSTRUCT(
               'status', 'OK', 'run_id', :run_id, 'target_db', :TARGET_DB,
               'injected', (SELECT OBJECT_AGG(CODE, tables) FROM (
                               SELECT CODE, OBJECT_AGG(TABLE_NAME, TO_VARIANT(AFFECTED_ROWS)) AS tables
                               FROM SUPPLY_CHAIN_FORGE.OPS.GEN_MESS_LOG WHERE RUN_ID = :run_id GROUP BY CODE)),
               'elapsed_s', DATEDIFF(millisecond, :run_t0, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ) / 1000)
      INTO :result;
    INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_LOG (RUN_ID, TARGET_DB, STAGE, TABLE_NAME, CHUNK, ROWS_WRITTEN, STARTED_AT, ENDED_AT)
    SELECT :run_id, :TARGET_DB, 'done', NULL, NULL, NULL, :run_t0, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ;
    RETURN result;

EXCEPTION
    WHEN OTHER THEN
        LET err_code VARCHAR := SQLCODE;
        LET err_msg VARCHAR := SQLERRM;
        INSERT INTO SUPPLY_CHAIN_FORGE.OPS.GEN_LOG (RUN_ID, TARGET_DB, STAGE, TABLE_NAME, CHUNK, ROWS_WRITTEN, STARTED_AT, ENDED_AT, PARAMS)
        SELECT COALESCE(:run_id, 'unknown'), :TARGET_DB, 'error', NULL, :stage, NULL, :run_t0, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
               OBJECT_CONSTRUCT('sqlcode', :err_code, 'sqlerrm', :err_msg);
        RETURN OBJECT_CONSTRUCT('status', 'ERROR', 'run_id', run_id, 'stage', stage, 'sqlcode', err_code, 'sqlerrm', err_msg);
END;
$$;
