-- ============================================================
-- seed_data.sql — Realistic supply chain sample data
-- Owner: CoCo
-- Run: After all table DDLs
-- ============================================================

-- TODO: CoCo will populate this file
-- Target volumes:
--   SUPPLIERS: 50+
--   PARTS: 200+
--   PLANTS: 10-15
--   CUSTOMERS: 100+
--   ORDERS: 500+ (spanning 12 months)
--   ORDER_ITEMS: 1500+
--   SHIPMENTS: 600+
--   INVENTORY: daily snapshots for 30 days across all plant-part combos
--
-- Data must support all four canonical metrics:
--   OTD: Mix of on-time and late deliveries (~85% OTD rate)
--   Fill Rate: Some partial fulfillments (~92% fill rate)
--   DOI: Varying inventory levels (15-45 days range)
--   Landed Cost: Varying freight/duty/handling across regions
