-- ============================================================
-- 02_roles_grants.sql — Persona roles, hierarchy, and grants
-- Task: B02
-- Owner: CoCo
-- Run: After 01_database.sql
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- 1. Create Core Roles
CREATE ROLE IF NOT EXISTS FORGE_ADMIN
    COMMENT = 'Supply Chain Forge administrator and object owner (full unmasked access)';

CREATE ROLE IF NOT EXISTS PLANNER_ROLE
    COMMENT = 'Production Planner persona role (inventory, orders, demand)';

CREATE ROLE IF NOT EXISTS BUYER_ROLE
    COMMENT = 'Procurement Lead persona role (suppliers, parts, sourcing)';

CREATE ROLE IF NOT EXISTS LOGISTICS_ROLE
    COMMENT = 'Logistics Coordinator persona role (shipments, delivery, carriers)';

-- 2. Role Hierarchy
-- Persona roles do NOT inherit one another (maintains strict persona isolation)
-- FORGE_ADMIN inherits all persona roles (for management and procedure execution)
GRANT ROLE PLANNER_ROLE TO ROLE FORGE_ADMIN;
GRANT ROLE BUYER_ROLE TO ROLE FORGE_ADMIN;
GRANT ROLE LOGISTICS_ROLE TO ROLE FORGE_ADMIN;

-- Grant FORGE_ADMIN up to system administrators
GRANT ROLE FORGE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE FORGE_ADMIN TO ROLE ACCOUNTADMIN;

-- Grant roles to current user
GRANT ROLE FORGE_ADMIN TO USER LAZYBOY;
GRANT ROLE PLANNER_ROLE TO USER LAZYBOY;
GRANT ROLE BUYER_ROLE TO USER LAZYBOY;
GRANT ROLE LOGISTICS_ROLE TO USER LAZYBOY;

-- 3. Database & Schema Grants for FORGE_ADMIN
GRANT USAGE, CREATE SCHEMA ON DATABASE SUPPLY_CHAIN_FORGE TO ROLE FORGE_ADMIN;
GRANT ALL PRIVILEGES ON DATABASE SUPPLY_CHAIN_FORGE TO ROLE FORGE_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SUPPLY_CHAIN_FORGE TO ROLE FORGE_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE SUPPLY_CHAIN_FORGE TO ROLE FORGE_ADMIN;

-- 4. Database & Schema Grants for Persona Roles
GRANT USAGE ON DATABASE SUPPLY_CHAIN_FORGE TO ROLE PLANNER_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_FORGE TO ROLE BUYER_ROLE;
GRANT USAGE ON DATABASE SUPPLY_CHAIN_FORGE TO ROLE LOGISTICS_ROLE;

-- Source Schemas USAGE
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.ERP_SOURCE TO ROLE PLANNER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.ERP_SOURCE TO ROLE BUYER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.ERP_SOURCE TO ROLE LOGISTICS_ROLE;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.WMS_SOURCE TO ROLE PLANNER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.WMS_SOURCE TO ROLE BUYER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.WMS_SOURCE TO ROLE LOGISTICS_ROLE;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.TMS_SOURCE TO ROLE PLANNER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.TMS_SOURCE TO ROLE BUYER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.TMS_SOURCE TO ROLE LOGISTICS_ROLE;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.SRM_SOURCE TO ROLE PLANNER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.SRM_SOURCE TO ROLE BUYER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.SRM_SOURCE TO ROLE LOGISTICS_ROLE;

-- Governed & Semantic Schemas USAGE
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.GOVERNED TO ROLE PLANNER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.GOVERNED TO ROLE BUYER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.GOVERNED TO ROLE LOGISTICS_ROLE;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.SEMANTIC TO ROLE PLANNER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.SEMANTIC TO ROLE BUYER_ROLE;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN_FORGE.SEMANTIC TO ROLE LOGISTICS_ROLE;

-- 5. Warehouse Grants
GRANT USAGE ON WAREHOUSE FORGE_WH TO ROLE FORGE_ADMIN;
GRANT USAGE ON WAREHOUSE FORGE_WH TO ROLE PLANNER_ROLE;
GRANT USAGE ON WAREHOUSE FORGE_WH TO ROLE BUYER_ROLE;
GRANT USAGE ON WAREHOUSE FORGE_WH TO ROLE LOGISTICS_ROLE;
GRANT USAGE ON WAREHOUSE FORGE_WH TO ROLE ACCOUNTADMIN;

-- 6. Schema Object Creation Privileges for FORGE_ADMIN
GRANT CREATE SEMANTIC VIEW ON SCHEMA SUPPLY_CHAIN_FORGE.SEMANTIC TO ROLE FORGE_ADMIN;
GRANT CREATE AGENT ON SCHEMA SUPPLY_CHAIN_FORGE.SEMANTIC TO ROLE FORGE_ADMIN;
GRANT CREATE STREAMLIT ON SCHEMA SUPPLY_CHAIN_FORGE.APP TO ROLE FORGE_ADMIN;
GRANT CREATE STAGE ON SCHEMA SUPPLY_CHAIN_FORGE.APP TO ROLE FORGE_ADMIN;

-- 7. Cortex Agent & Cortex User Database Role Grants
-- Note: Agents use default role (LAZYBOY default is ACCOUNTADMIN)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE FORGE_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE ACCOUNTADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE FORGE_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE PLANNER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE BUYER_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE LOGISTICS_ROLE;

-- 8. Session Context Grant (Required for CURRENT_ROLE evaluation in SiS & procedures)
GRANT READ SESSION ON ACCOUNT TO ROLE FORGE_ADMIN;
