-- ============================================================================
-- tests/scale/10_scale_queries.sql — OPS.SCALE_QUERIES: every query the core system sends
-- Card:       C12 (.agents/tasks/claude/C12_scale_harness.md)
-- Spec:       docs/DATA_SPEC.md §7.4, docs/CONTRACT.md §3a, §4, §5, §8
-- Role:       FORGE_ADMIN        Warehouse: FORGE_WH
-- Run order:  2 of 4 (00 → 10 → 20 → 99). Re-runnable: CREATE OR REPLACE, then the rows.
-- Expected:   75 rows (70 active, 5 AGENT rows inactive until B13 has a clone-local agent).
--
-- GENERATED by tests/scale/build_scale_queries.py from the app's own SQL builders
-- (forge_data.build_metric_sql, NAIVE_OTD_SQL, build_call_sql, build_agent_sql). Do not edit
-- by hand: change the app, re-run the generator. tests/unit/test_scale_sql.py checks it.
-- {{DB}} is replaced by SP_SCALE_RUN's TARGET_DB. SQL_HASH = HASH(SQL_TEMPLATE), so an
-- identical hash in every run proves the same SQL ran at every scale.
-- HASH_EXPR is what HASH_AGG fingerprints in the result (numbers rounded to 6 dp).
-- ============================================================================

CREATE OR REPLACE TABLE SUPPLY_CHAIN_FORGE.OPS.SCALE_QUERIES (
    QUERY_NAME    VARCHAR   NOT NULL COMMENT 'Stable name, e.g. SV_FILL_RATE_BY_PARTS__CATEGORY',
    SORT_ORDER    NUMBER    NOT NULL,
    PATH          VARCHAR   NOT NULL COMMENT 'SEMANTIC_VIEW, PROCEDURE, NAIVE or AGENT',
    METRIC        VARCHAR            COMMENT 'Contract metric key',
    DIMENSION     VARCHAR            COMMENT 'Contract dimension, e.g. plants.plant_region',
    TIME_WINDOW   VARCHAR            COMMENT 'ALL, T12M (the §3a trailing 12 months) or LATEST (DOI snapshot)',
    SQL_TEMPLATE  VARCHAR   NOT NULL COMMENT 'The query, with {{DB}} for the database name',
    HASH_EXPR     VARCHAR            COMMENT 'Columns HASH_AGG fingerprints in the result, NULL = not fingerprinted',
    ACTIVE        BOOLEAN   NOT NULL
)
COMMENT = 'C12: the scale harness query catalogue (generated from the app, DATA_SPEC §7.4)';

INSERT INTO SUPPLY_CHAIN_FORGE.OPS.SCALE_QUERIES
SELECT column1, column2, column3, column4, column5, column6, column7, column8, column9
FROM VALUES
    ('SV_ON_TIME_DELIVERY_RATE_ALL', 1, 'SEMANTIC_VIEW', 'on_time_delivery_rate', NULL, 'ALL', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS shipments.on_time_delivery_rate
)$$, 'ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_FILL_RATE_ALL', 2, 'SEMANTIC_VIEW', 'fill_rate', NULL, 'ALL', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS order_lines.fill_rate
)$$, 'ROUND(FILL_RATE, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_ALL', 3, 'SEMANTIC_VIEW', 'days_of_inventory', NULL, 'ALL', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS inventory.days_of_inventory
)$$, 'ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_AVG_LANDED_COST_ALL', 4, 'SEMANTIC_VIEW', 'avg_landed_cost', NULL, 'ALL', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS shipments.avg_landed_cost
)$$, 'ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_DEFAULT', 5, 'SEMANTIC_VIEW', 'on_time_delivery_rate', NULL, 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
)$$, 'ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_FILL_RATE_DEFAULT', 6, 'SEMANTIC_VIEW', 'fill_rate', NULL, 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
)$$, 'ROUND(FILL_RATE, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_DEFAULT', 7, 'SEMANTIC_VIEW', 'days_of_inventory', NULL, 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
)$$, 'ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_AVG_LANDED_COST_DEFAULT', 8, 'SEMANTIC_VIEW', 'avg_landed_cost', NULL, 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
)$$, 'ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_PLANTS__PLANT_NAME', 9, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'plants.plant_name', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_name
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_name$$, 'PLANT_NAME, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_PLANTS__PLANT_REGION', 10, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'plants.plant_region', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_region
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_region$$, 'PLANT_REGION, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_PLANTS__PLANT_COUNTRY', 11, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'plants.plant_country', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_country
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_country$$, 'PLANT_COUNTRY, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_PLANTS__PLANT_TYPE', 12, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'plants.plant_type', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_type
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_type$$, 'PLANT_TYPE, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_ORDERS__ORDER_DATE', 13, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'orders.order_date', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_date
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_date$$, 'ORDER_DATE, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_ORDERS__ORDER_MONTH', 14, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'orders.order_month', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_month
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_month$$, 'ORDER_MONTH, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_ORDERS__ORDER_QUARTER', 15, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'orders.order_quarter', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_quarter
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_quarter$$, 'ORDER_QUARTER, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_ORDERS__ORDER_YEAR', 16, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'orders.order_year', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_year
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_year$$, 'ORDER_YEAR, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_ORDERS__ORDER_YEAR_QUARTER', 17, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'orders.order_year_quarter', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_year_quarter
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_year_quarter$$, 'ORDER_YEAR_QUARTER, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_ORDERS__ORDER_STATUS', 18, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'orders.order_status', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_status
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_status$$, 'ORDER_STATUS, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_ORDERS__ORDER_PRIORITY', 19, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'orders.order_priority', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_priority
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_priority$$, 'ORDER_PRIORITY, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_SHIPMENTS__SHIP_DATE', 20, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'shipments.ship_date', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS shipments.ship_date
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY ship_date$$, 'SHIP_DATE, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_SHIPMENTS__CARRIER', 21, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'shipments.carrier', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS shipments.carrier
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY carrier$$, 'CARRIER, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_SHIPMENTS__SHIPMENT_STATUS', 22, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'shipments.shipment_status', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS shipments.shipment_status
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY shipment_status$$, 'SHIPMENT_STATUS, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_CUSTOMERS__CUSTOMER_SEGMENT', 23, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'customers.customer_segment', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS customers.customer_segment
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY customer_segment$$, 'CUSTOMER_SEGMENT, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_ON_TIME_DELIVERY_RATE_BY_CUSTOMERS__CUSTOMER_REGION', 24, 'SEMANTIC_VIEW', 'on_time_delivery_rate', 'customers.customer_region', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS customers.customer_region
  METRICS shipments.on_time_delivery_rate
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY customer_region$$, 'CUSTOMER_REGION, ROUND(ON_TIME_DELIVERY_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PARTS__PART_NAME', 25, 'SEMANTIC_VIEW', 'fill_rate', 'parts.part_name', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.part_name
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY part_name$$, 'PART_NAME, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PARTS__CATEGORY', 26, 'SEMANTIC_VIEW', 'fill_rate', 'parts.category', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.category
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY category$$, 'CATEGORY, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PARTS__SUBCATEGORY', 27, 'SEMANTIC_VIEW', 'fill_rate', 'parts.subcategory', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.subcategory
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY subcategory$$, 'SUBCATEGORY, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PARTS__IS_CRITICAL', 28, 'SEMANTIC_VIEW', 'fill_rate', 'parts.is_critical', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.is_critical
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY is_critical$$, 'IS_CRITICAL, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PLANTS__PLANT_NAME', 29, 'SEMANTIC_VIEW', 'fill_rate', 'plants.plant_name', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_name
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY plant_name$$, 'PLANT_NAME, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PLANTS__PLANT_REGION', 30, 'SEMANTIC_VIEW', 'fill_rate', 'plants.plant_region', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_region
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY plant_region$$, 'PLANT_REGION, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PLANTS__PLANT_COUNTRY', 31, 'SEMANTIC_VIEW', 'fill_rate', 'plants.plant_country', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_country
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY plant_country$$, 'PLANT_COUNTRY, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_PLANTS__PLANT_TYPE', 32, 'SEMANTIC_VIEW', 'fill_rate', 'plants.plant_type', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_type
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY plant_type$$, 'PLANT_TYPE, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_ORDERS__ORDER_DATE', 33, 'SEMANTIC_VIEW', 'fill_rate', 'orders.order_date', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_date
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY order_date$$, 'ORDER_DATE, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_ORDERS__ORDER_MONTH', 34, 'SEMANTIC_VIEW', 'fill_rate', 'orders.order_month', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_month
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY order_month$$, 'ORDER_MONTH, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_ORDERS__ORDER_QUARTER', 35, 'SEMANTIC_VIEW', 'fill_rate', 'orders.order_quarter', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_quarter
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY order_quarter$$, 'ORDER_QUARTER, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_ORDERS__ORDER_YEAR', 36, 'SEMANTIC_VIEW', 'fill_rate', 'orders.order_year', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_year
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY order_year$$, 'ORDER_YEAR, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_ORDERS__ORDER_YEAR_QUARTER', 37, 'SEMANTIC_VIEW', 'fill_rate', 'orders.order_year_quarter', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_year_quarter
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY order_year_quarter$$, 'ORDER_YEAR_QUARTER, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_ORDERS__ORDER_STATUS', 38, 'SEMANTIC_VIEW', 'fill_rate', 'orders.order_status', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_status
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY order_status$$, 'ORDER_STATUS, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_ORDERS__ORDER_PRIORITY', 39, 'SEMANTIC_VIEW', 'fill_rate', 'orders.order_priority', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_priority
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY order_priority$$, 'ORDER_PRIORITY, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_CUSTOMERS__CUSTOMER_SEGMENT', 40, 'SEMANTIC_VIEW', 'fill_rate', 'customers.customer_segment', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS customers.customer_segment
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY customer_segment$$, 'CUSTOMER_SEGMENT, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_FILL_RATE_BY_CUSTOMERS__CUSTOMER_REGION', 41, 'SEMANTIC_VIEW', 'fill_rate', 'customers.customer_region', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS customers.customer_region
  METRICS order_lines.fill_rate
  WHERE orders.order_date > DATEADD(month, -12, CURRENT_DATE())
    AND orders.order_date <= CURRENT_DATE()
) ORDER BY customer_region$$, 'CUSTOMER_REGION, ROUND(FILL_RATE, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PLANTS__PLANT_NAME', 42, 'SEMANTIC_VIEW', 'days_of_inventory', 'plants.plant_name', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_name
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY plant_name$$, 'PLANT_NAME, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PLANTS__PLANT_REGION', 43, 'SEMANTIC_VIEW', 'days_of_inventory', 'plants.plant_region', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_region
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY plant_region$$, 'PLANT_REGION, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PLANTS__PLANT_COUNTRY', 44, 'SEMANTIC_VIEW', 'days_of_inventory', 'plants.plant_country', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_country
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY plant_country$$, 'PLANT_COUNTRY, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PLANTS__PLANT_TYPE', 45, 'SEMANTIC_VIEW', 'days_of_inventory', 'plants.plant_type', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_type
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY plant_type$$, 'PLANT_TYPE, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PARTS__PART_NAME', 46, 'SEMANTIC_VIEW', 'days_of_inventory', 'parts.part_name', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.part_name
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY part_name$$, 'PART_NAME, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PARTS__CATEGORY', 47, 'SEMANTIC_VIEW', 'days_of_inventory', 'parts.category', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.category
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY category$$, 'CATEGORY, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PARTS__SUBCATEGORY', 48, 'SEMANTIC_VIEW', 'days_of_inventory', 'parts.subcategory', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.subcategory
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY subcategory$$, 'SUBCATEGORY, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_PARTS__IS_CRITICAL', 49, 'SEMANTIC_VIEW', 'days_of_inventory', 'parts.is_critical', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS parts.is_critical
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY is_critical$$, 'IS_CRITICAL, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_DAYS_OF_INVENTORY_BY_INVENTORY__SNAPSHOT_DATE', 50, 'SEMANTIC_VIEW', 'days_of_inventory', 'inventory.snapshot_date', 'LATEST', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS inventory.snapshot_date
  METRICS inventory.days_of_inventory
  WHERE inventory.snapshot_date = (SELECT MAX(snapshot_date) FROM {{DB}}.GOVERNED.V_INVENTORY)
) ORDER BY snapshot_date$$, 'SNAPSHOT_DATE, ROUND(DAYS_OF_INVENTORY, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_PLANTS__PLANT_NAME', 51, 'SEMANTIC_VIEW', 'avg_landed_cost', 'plants.plant_name', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_name
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_name$$, 'PLANT_NAME, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_PLANTS__PLANT_REGION', 52, 'SEMANTIC_VIEW', 'avg_landed_cost', 'plants.plant_region', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_region
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_region$$, 'PLANT_REGION, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_PLANTS__PLANT_COUNTRY', 53, 'SEMANTIC_VIEW', 'avg_landed_cost', 'plants.plant_country', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_country
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_country$$, 'PLANT_COUNTRY, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_PLANTS__PLANT_TYPE', 54, 'SEMANTIC_VIEW', 'avg_landed_cost', 'plants.plant_type', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS plants.plant_type
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY plant_type$$, 'PLANT_TYPE, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_ORDERS__ORDER_DATE', 55, 'SEMANTIC_VIEW', 'avg_landed_cost', 'orders.order_date', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_date
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_date$$, 'ORDER_DATE, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_ORDERS__ORDER_MONTH', 56, 'SEMANTIC_VIEW', 'avg_landed_cost', 'orders.order_month', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_month
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_month$$, 'ORDER_MONTH, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_ORDERS__ORDER_QUARTER', 57, 'SEMANTIC_VIEW', 'avg_landed_cost', 'orders.order_quarter', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_quarter
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_quarter$$, 'ORDER_QUARTER, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_ORDERS__ORDER_YEAR', 58, 'SEMANTIC_VIEW', 'avg_landed_cost', 'orders.order_year', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_year
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_year$$, 'ORDER_YEAR, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_ORDERS__ORDER_YEAR_QUARTER', 59, 'SEMANTIC_VIEW', 'avg_landed_cost', 'orders.order_year_quarter', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_year_quarter
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_year_quarter$$, 'ORDER_YEAR_QUARTER, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_ORDERS__ORDER_STATUS', 60, 'SEMANTIC_VIEW', 'avg_landed_cost', 'orders.order_status', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_status
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_status$$, 'ORDER_STATUS, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_ORDERS__ORDER_PRIORITY', 61, 'SEMANTIC_VIEW', 'avg_landed_cost', 'orders.order_priority', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS orders.order_priority
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY order_priority$$, 'ORDER_PRIORITY, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_SHIPMENTS__SHIP_DATE', 62, 'SEMANTIC_VIEW', 'avg_landed_cost', 'shipments.ship_date', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS shipments.ship_date
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY ship_date$$, 'SHIP_DATE, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_SHIPMENTS__CARRIER', 63, 'SEMANTIC_VIEW', 'avg_landed_cost', 'shipments.carrier', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS shipments.carrier
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY carrier$$, 'CARRIER, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_SHIPMENTS__SHIPMENT_STATUS', 64, 'SEMANTIC_VIEW', 'avg_landed_cost', 'shipments.shipment_status', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS shipments.shipment_status
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY shipment_status$$, 'SHIPMENT_STATUS, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_CUSTOMERS__CUSTOMER_SEGMENT', 65, 'SEMANTIC_VIEW', 'avg_landed_cost', 'customers.customer_segment', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS customers.customer_segment
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY customer_segment$$, 'CUSTOMER_SEGMENT, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('SV_AVG_LANDED_COST_BY_CUSTOMERS__CUSTOMER_REGION', 66, 'SEMANTIC_VIEW', 'avg_landed_cost', 'customers.customer_region', 'T12M', $$SELECT * FROM SEMANTIC_VIEW(
  {{DB}}.SEMANTIC.SUPPLY_CHAIN_SV
  DIMENSIONS customers.customer_region
  METRICS shipments.avg_landed_cost
  WHERE shipments.ship_date > DATEADD(month, -12, CURRENT_DATE())
    AND shipments.ship_date <= CURRENT_DATE()
) ORDER BY customer_region$$, 'CUSTOMER_REGION, ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('PROC_METRICS_AS_PLANNER', 67, 'PROCEDURE', NULL, NULL, 'T12M', $$CALL {{DB}}.GOVERNED.SP_METRICS_AS_PLANNER()$$, 'ROUND(ON_TIME_DELIVERY_RATE, 6), ROUND(FILL_RATE, 6), ROUND(DAYS_OF_INVENTORY, 6), ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('PROC_METRICS_AS_BUYER', 68, 'PROCEDURE', NULL, NULL, 'T12M', $$CALL {{DB}}.GOVERNED.SP_METRICS_AS_BUYER()$$, 'ROUND(ON_TIME_DELIVERY_RATE, 6), ROUND(FILL_RATE, 6), ROUND(DAYS_OF_INVENTORY, 6), ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('PROC_METRICS_AS_LOGISTICS', 69, 'PROCEDURE', NULL, NULL, 'T12M', $$CALL {{DB}}.GOVERNED.SP_METRICS_AS_LOGISTICS()$$, 'ROUND(ON_TIME_DELIVERY_RATE, 6), ROUND(FILL_RATE, 6), ROUND(DAYS_OF_INVENTORY, 6), ROUND(AVG_LANDED_COST, 6)', TRUE),
    ('NAIVE_OTD', 70, 'NAIVE', 'on_time_delivery_rate', NULL, 'T12M', $$SELECT COUNT_IF(s.ACT_DLV_DT <= o.ERDAT) / NULLIFZERO(COUNT_IF(s.ACT_DLV_DT IS NOT NULL))
FROM {{DB}}.TMS_SOURCE.VTTK s
JOIN {{DB}}.ERP_SOURCE.VBAK o ON s.VBELN = o.VBELN
WHERE s.DPTBG > DATEADD(month, -12, CURRENT_DATE()) AND s.DPTBG <= CURRENT_DATE()$$, 'ROUND($1, 6)', TRUE),
    ('AGENT_Q1', 71, 'AGENT', NULL, NULL, NULL, $$SELECT TRY_PARSE_JSON(
  SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
    '{{DB}}.SEMANTIC.SUPPLY_CHAIN_AGENT',
    '{"messages": [{"role": "user", "content": [{"type": "text", "text": "What is our overall on-time delivery rate?"}]}]}',
    TRUE
  )
) AS response$$, NULL, FALSE),
    ('AGENT_Q2', 72, 'AGENT', NULL, NULL, NULL, $$SELECT TRY_PARSE_JSON(
  SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
    '{{DB}}.SEMANTIC.SUPPLY_CHAIN_AGENT',
    '{"messages": [{"role": "user", "content": [{"type": "text", "text": "What is on-time delivery rate by region?"}]}]}',
    TRUE
  )
) AS response$$, NULL, FALSE),
    ('AGENT_Q3', 73, 'AGENT', NULL, NULL, NULL, $$SELECT TRY_PARSE_JSON(
  SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
    '{{DB}}.SEMANTIC.SUPPLY_CHAIN_AGENT',
    '{"messages": [{"role": "user", "content": [{"type": "text", "text": "What is fill rate by product category?"}]}]}',
    TRUE
  )
) AS response$$, NULL, FALSE),
    ('AGENT_Q4', 74, 'AGENT', NULL, NULL, NULL, $$SELECT TRY_PARSE_JSON(
  SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
    '{{DB}}.SEMANTIC.SUPPLY_CHAIN_AGENT',
    '{"messages": [{"role": "user", "content": [{"type": "text", "text": "What is average landed cost by region?"}]}]}',
    TRUE
  )
) AS response$$, NULL, FALSE),
    ('AGENT_Q5', 75, 'AGENT', NULL, NULL, NULL, $$SELECT TRY_PARSE_JSON(
  SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
    '{{DB}}.SEMANTIC.SUPPLY_CHAIN_AGENT',
    '{"messages": [{"role": "user", "content": [{"type": "text", "text": "Show the on-time delivery rate by order priority."}]}]}',
    TRUE
  )
) AS response$$, NULL, FALSE);
