"""C12: generates tests/scale/10_scale_queries.sql, the scale harness's query catalogue,
from the app's own SQL builders. Every query the core system sends, with the database name
replaced by {{DB}} so one catalogue runs against the original or a clone.

Run from the repo root after any change to the app's queries or the contract pairings:
    .venv/Scripts/python tests/scale/build_scale_queries.py
tests/unit/test_scale_sql.py fails if the committed file differs from this output.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "app"))

from utils import config, forge_data  # noqa: E402

OUT = ROOT / "tests" / "scale" / "10_scale_queries.sql"
DB = config.DATABASE
AGENT_QUESTIONS = [0, 1, 4, 6]  # indexes into config.CANONICAL_QUESTIONS, plus one cross-system question below
CROSS_SYSTEM = "Show the on-time delivery rate by order priority."


def templated(sql: str) -> str:
    return sql.replace(f"{DB}.", "{{DB}}.")


def metric_col(key: str) -> str:
    return config.METRICS[key]["id"].split(".")[1].upper()


def slug(text: str) -> str:
    return text.replace(".", "__").upper()


def queries() -> list[dict]:
    rows = []

    def add(name, path, sql, hash_expr, metric=None, dimension=None, window=None, active=True):
        rows.append(dict(name=name, path=path, metric=metric, dimension=dimension, window=window,
                         sql=templated(sql), hash_expr=hash_expr, active=active))

    # The 4 metrics, all-time and in the §3a default window (DOI: the latest snapshot).
    for key, m in config.METRICS.items():
        add(f"SV_{key.upper()}_ALL", "SEMANTIC_VIEW",
            f"SELECT * FROM SEMANTIC_VIEW(\n  {config.SEMANTIC_VIEW}\n  METRICS {m['id']}\n)",
            f"ROUND({metric_col(key)}, 6)", key, None, "ALL")
    for key in config.METRICS:
        add(f"SV_{key.upper()}_DEFAULT", "SEMANTIC_VIEW", forge_data.build_metric_sql(key),
            f"ROUND({metric_col(key)}, 6)", key, None, "LATEST" if key not in config.WINDOW_DATE else "T12M")
    # Every valid metric × dimension pairing, default window: exactly the app's query.
    for key, dims in config.VALID_PAIRINGS.items():
        for dim in dims:
            add(f"SV_{key.upper()}_BY_{slug(dim)}", "SEMANTIC_VIEW", forge_data.build_metric_sql(key, dim),
                f"{config.column_name(dim)}, ROUND({metric_col(key)}, 6)", key, dim,
                "LATEST" if key not in config.WINDOW_DATE else "T12M")
    # The persona procedures: the persona column is left out of the fingerprint, so the three
    # fingerprints are equal exactly when the numbers are.
    persona_hash = ", ".join(f"ROUND({metric_col(k)}, 6)" for k in config.METRICS)
    for persona, proc in config.PERSONA_METRIC_PROCS.items():
        add(f"PROC_METRICS_AS_{persona.upper()}", "PROCEDURE", forge_data.build_call_sql(proc), persona_hash,
            None, None, "T12M")
    # The one naive query on the raw source tables (contract §8).
    add("NAIVE_OTD", "NAIVE", forge_data.NAIVE_OTD_SQL, "ROUND($1, 6)", "on_time_delivery_rate", None, "T12M")
    # A few agent questions: inactive until B13 has a clone-local agent. Answers aren't
    # fingerprinted (the wording varies); only the timing matters.
    agent_sql = forge_data.build_agent_sql()
    for n, question in enumerate([config.CANONICAL_QUESTIONS[i] for i in AGENT_QUESTIONS] + [CROSS_SYSTEM], 1):
        # CR-007: the whole request JSON as one constant (a string literal works live)
        literal = "'" + forge_data.agent_request(question).replace("'", "''") + "'"
        add(f"AGENT_Q{n}", "AGENT", agent_sql.replace("?", literal), None, active=False)
    return rows


def lit(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def dollar(sql: str) -> str:
    assert "$$" not in sql
    return "$$" + sql + "$$"


HEADER = """-- ============================================================================
-- tests/scale/10_scale_queries.sql — OPS.SCALE_QUERIES: every query the core system sends
-- Card:       C12 (.agents/tasks/claude/C12_scale_harness.md)
-- Spec:       docs/DATA_SPEC.md §7.4, docs/CONTRACT.md §3a, §4, §5, §8
-- Role:       FORGE_ADMIN        Warehouse: FORGE_WH
-- Run order:  2 of 4 (00 → 10 → 20 → 99). Re-runnable: CREATE OR REPLACE, then the rows.
-- Expected:   {n} rows ({active} active, {agent} AGENT rows inactive until B13 has a clone-local agent).
--
-- GENERATED by tests/scale/build_scale_queries.py from the app's own SQL builders
-- (forge_data.build_metric_sql, NAIVE_OTD_SQL, build_call_sql, build_agent_sql). Do not edit
-- by hand: change the app, re-run the generator. tests/unit/test_scale_sql.py checks it.
-- {{{{DB}}}} is replaced by SP_SCALE_RUN's TARGET_DB. SQL_HASH = HASH(SQL_TEMPLATE), so an
-- identical hash in every run proves the same SQL ran at every scale.
-- HASH_EXPR is what HASH_AGG fingerprints in the result (numbers rounded to 6 dp).
-- ============================================================================

CREATE OR REPLACE TABLE SUPPLY_CHAIN_FORGE.OPS.SCALE_QUERIES (
    QUERY_NAME    VARCHAR   NOT NULL COMMENT 'Stable name, e.g. SV_FILL_RATE_BY_PARTS__CATEGORY',
    SORT_ORDER    NUMBER    NOT NULL,
    PATH          VARCHAR   NOT NULL COMMENT 'SEMANTIC_VIEW, PROCEDURE, NAIVE or AGENT',
    METRIC        VARCHAR            COMMENT 'Contract metric key',
    DIMENSION     VARCHAR            COMMENT 'Contract dimension, e.g. plants.plant_region',
    TIME_WINDOW   VARCHAR            COMMENT 'ALL, T12M (the §3a trailing 12 months) or LATEST (DOI snapshot)',
    SQL_TEMPLATE  VARCHAR   NOT NULL COMMENT 'The query, with {{{{DB}}}} for the database name',
    HASH_EXPR     VARCHAR            COMMENT 'Columns HASH_AGG fingerprints in the result, NULL = not fingerprinted',
    ACTIVE        BOOLEAN   NOT NULL
)
COMMENT = 'C12: the scale harness query catalogue (generated from the app, DATA_SPEC §7.4)';

INSERT INTO SUPPLY_CHAIN_FORGE.OPS.SCALE_QUERIES
SELECT column1, column2, column3, column4, column5, column6, column7, column8, column9
FROM VALUES
"""


def render() -> str:
    rows = queries()
    body = ",\n".join(
        "    (" + ", ".join([lit(r["name"]), str(i), lit(r["path"]), lit(r["metric"]), lit(r["dimension"]),
                             lit(r["window"]), dollar(r["sql"]), lit(r["hash_expr"]), lit(r["active"])]) + ")"
        for i, r in enumerate(rows, 1))
    head = HEADER.format(n=len(rows), active=sum(r["active"] for r in rows),
                         agent=sum(r["path"] == "AGENT" for r in rows))
    return head + body + ";\n"


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(queries())} queries")
